# Generated by Django 4.2.16 on 2024-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0002_profile_username_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='x.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='vecteezy_kid-play-table-tennis_48115843.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
