# Generated by Django 4.2.16 on 2024-11-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0006_alter_friendshiprequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
    ]
