# Generated by Django 4.2.16 on 2024-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0007_remove_profile_bio_remove_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='/static/assets/imgs/user_avatar.png', max_length=255),
        ),
    ]
